
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Button } from "@heroui/react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const links = <>
    <li> <Link href={'/'}>Home</Link> </li>
    <li> <Link href={'/users'}>Users</Link> </li>
    <li> <Link href={'/about'}>About</Link> </li>
    <li> <Link href={'/posts'}>Posts</Link> </li>

  </>
  return (
    <html
      lang="en"
      className= {`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Navbar  */}
          
          {children}
      </body>
    </html>
  );
}
